prompt_order = [
    "username",
    "hostname",
    "directory",
    "git_branch",
    "git_commit",
    "git_state",
    "git_status",
    "package",
    "golang",
    "python",
    "rust",
    "aws",
    "kubernetes",
    "terraform",
    "cmd_duration",
    "line_break",
    "jobs",
    "battery",
    "time",
    "character",
]

[hostname]
prefix = "歷"
style = "#FF8800"

# Replace the "❯" symbol in the prompt with "➜"
[character]      # The name of the module we are configuring is "character"
symbol = "➜ "    # The "symbol" segment is being set to "➜"

# The cLOUD! onward and upward!
# --------------------
[aws]
symbol = " "

# Laptoppy
# --------------------
[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""

# commad duration
[cmd_duration]
min_time = 5000

# Git Stuff
# --------------------
# Enable Git commit
[git_commit]
disabled = false
style = "yellow"
prefix = " "
suffix = " "
commit_hash_length = 7

[git_branch]
symbol = " "
style = "bold green"
truncation_length = 8


# Kubernetes
# --------------------
[kubernetes]
symbol = " "
disabled = false
style = "bold #326CE5"

[golang]
symbol = " "
style = "bold ##00ADD8"

[package]
symbol = " "
style = "bold green"

[python]
symbol = " "
style = "#FFD43B"

[rust]
symbol = " "
style = "#DEA584"

[terraform]
style = "#623CE4"

# Disable not needed features
# --------------------
[conda]
disabled = true

[dotnet]
disabled = true

[env_var]
disabled = true

[hg_branch]
disabled = true

[java]
disabled = true

[ruby]
disabled = true

[nix_shell]
disabled = true

[memory_usage]
disabled = true

# Because F**** nodejs, its worse than PHP
[nodejs]
disabled = true

[php]
disabled = true
