# yamllint disable-line rule:document-start
on:
  push:
    branches:
      - master
      - stable
    paths-ignore:
      - ".gitignore"
      - ".editorconfig"
      - ".envrc"
      - "**.md"
      - ".vscode/**"
  pull_request:
    branches:
      - master
name: lint
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Shellcheck
        run: make shellcheck
      - name: Test Install script
        run: |
          ./checksum.sh --verify -G
          # Modify after verification
          sed -i 's/set -o pipefail/set -eo pipefail/g' ./install.sh
          ./install.sh -i -x --test-mode
          ./install.sh -i -x
          ./install.sh -i -n hpc -T
